<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DAMERP1-TL2" ignored="0" name="Test" tests="6" failures="2" timestamp="2021-12-02T13:38:37 IST" time="0.056" errors="0">
  <testcase name="five" time="0.007" classname="com.testNG.examples.AssetionExamples"/>
  <testcase name="four" time="0.004" classname="com.testNG.examples.AssetionExamples">
    <failure type="java.lang.AssertionError" message="Making Test Failure expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Making Test Failure expected [true] but found [false]
at com.testNG.examples.AssetionExamples.four(AssetionExamples.java:33)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- four -->
  <testcase name="one" time="0.001" classname="com.testNG.examples.AssetionExamples"/>
  <testcase name="six" time="0.0" classname="com.testNG.examples.AssetionExamples"/>
  <testcase name="three" time="0.002" classname="com.testNG.examples.AssetionExamples"/>
  <testcase name="two" time="0.001" classname="com.testNG.examples.AssetionExamples">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at com.testNG.examples.AssetionExamples.two(AssetionExamples.java:18)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- two -->
</testsuite> <!-- Test -->
